### ISSUE TITLE
小白用户想问问作者有没有使用例子呢？

### ISSUE THREAD

**Issue by yahuian** [ginuerzh/tls-dissector#2]
我的需求是获取指定目标的 tls 握手信息，经过一番研究，发现通过 go tls 标准库只能获取到证书，不能得到中间过程的握手信息。
想问问您这个库有没有使用例子可供参考，谢谢啦～

**Comment by ginuerzh** [comment]
可以参考下
https://github.com/ginuerzh/gost/blob/master/sni.go#L69

**Comment by yahuian** [comment]
谢谢大佬，我去研究研究 😁

**Comment by yahuian** [comment]
大佬，能推荐一些资料或者 demo 吗？看了好几天，感觉摸不到头绪🤒
